config/routes.rb
Drivein::Application.routes.draw do
  
  resources :relationships
  resources :sessions, only: [:new, :create, :destroy]
  match '/signup', to: 'users#new'
  match '/signin', to: 'sessions#new'
  match '/signout', to: 'sessions#destroy', via: :delete
  resources :admins, only: [:new, :create, :destroy]
  root to: 'admins#hello'

  match '/about', to: 'home#about'
  match '/contact', to: 'home#contact'
  match '/home', to: 'home#index'
  match '/channel', to: 'home#channel'
  match '/learn', to: 'home#learn'
  match '/news', to: 'home#news'
  
  match '/theatre', to: 'wireframe#theatre'
  match '/screening_room', to: 'wireframe#screening_room'
  match '/cutting_room', to: 'wireframe#cutting_room'
  match '/suitcase', to: 'wireframe#suitcase'
  match '/tabloids', to: 'wireframe#tabloids'
  match '/surf', to: 'wireframe#surf'
  
  resources :microposts, only: [:create, :destroy]
  resources :relationships, only: [:create, :destroy]
  
  resources :users do 
    member do
      get :following, :followers
    end
  end
  

end

app/views/shared/_custom_controls_player.html.erb
<% full_url = "../assets/video/#{@video.url}" %>
<p><%= full_url %></p>

<video id="videoShow" controls width="<%= @video.width %>" height ="<%= @video.height %>" preload="auto" poster="<%= full_url %>.jpg">
  <source src="<%= full_url %>.mp4" type="video/mp4" />
  <source src="<%= full_url %>.ogv" type="video/ogg" />
  <p>Your browser does not support video</p>
  
</video>

<div id="video_controls">
  <div id="play_toggle" class="player-button">Play</div>
  <div id="progress">
    <div id="load_progress"></div>
    <div id="play_progress"></div>
  </div>
  <div id="time">
    <span id="current_time">00:00</span> /
    <span id="duration">00:00</span>
  </div> 
</div>

<script>
  $('#videoShow').bind("ended", function() {
    this.play();
  });
  
  $(function() {
    
    // doesnt render controls if HTML5 video type is not supported //
    if (!document.createElement('video').canPlayType) {
      $('#video_controls').hide();
      return;
    }

    var video = document.getElementById('videoShow');
    
    // Play/Pause button ===========================================//
    $("#play_toggle").bind('click', function() {
      if (video.paused) {
        video.play();
        $(this).html("Pause");
      } else {
        video.pause();
        $(this).html("Play");
      }
    });
    
    // Progress Bar code ===========================================//
    $("#videoShow").bind("timeupdate", function() {
      var timePercent = (this.currentTime / this.duration) * 100;
      $("#play_progress").css({ width : timePercent + "%" });
    });
    
    $(video).bind("progress", function() {
      updateLoadProgress(this);
    });
    $(video).bind("loadeddata", function() {
      updateLoadProgress(this);
    });
    $(video).bind("canplaythrough", function() {
      updateLoadProgress(this);
    });
    $(video).bind("playing", function() {
      updateLoadProgress(this);
    });
    
    function updateLoadProgress(video_player) {
      if (video_player.buffered.length > 0) {
        var percent = (video_player.buffered.end(0) / video_player.duration) * 100;
        $('#load_progress').css({ width: percent + '%'});
      } 
    }
    
    // Time Display ==================================================//
    $(video).bind("timeupdate", function() {
      $("#current_time").html(formatTime(this.currentTime));
    });
    $(video).bind("durationchange", function() {
      $("#duration").html(formatTime(this.duration));
    });
    function formatTime(seconds) {
      var seconds = Math.round(seconds);
      var minutes = Math.floor(seconds / 60);
      seconds = Math.floor(seconds % 60);
      minutes = (minutes >= 10) ? minutes : "0" + minutes;
      seconds = (seconds >= 10) ? seconds : "0" + seconds;
      return minutes + ":" + seconds;
    }
    
  });
  


</script>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-error">
      The form contains <%= pluralize(@user.errors.count, "error") %>.
    </div>
    <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li>* <%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_feed.html.erb
<% if @feed_items.any? %>
  <ol class="microposts">
    <%= render partial: 'shared/feed_item', collection: @feed_items %>
  </ol>
<% end %>

app/views/shared/_feed_item.html.erb
<% if feed_item.video.nil? %>
  <li id="<%= feed_item.id %>">
    <%= link_to gravatar_for(feed_item.user), feed_item.user %>
    <span class="user">
      <%= link_to feed_item.user.name, feed_item.user %>
    </span>
    <span class="content"><%= feed_item.content %></span>
    <span class="timestamp">
      Posted <%= time_ago_in_words(feed_item.created_at) %> ago.
      <% if current_user?(feed_item.user) %>
      <%= link_to "delete", feed_item, method: :delete,
        confirm: "You sure?",
        title: feed_item.content %>
      <% end %>
    </span>
  </li>
<% else %>
  <li id="<%= feed_item.id %>">
    <%= link_to gravatar_for(feed_item.user), feed_item.user %>
    <span class="user">
      <%= link_to feed_item.user.name, feed_item.user %></span>
    <div>
      <% @video = feed_item.video %>
      <%= render 'shared/feed_player',video: @video  %>
    </div>
    <span class="video_link"><%= link_to feed_item.video.url, feed_item.video %>
    </span>
    <span class="content"><%= feed_item.content %></span>
    <span class="timestamp">
      Posted <%= time_ago_in_words(feed_item.created_at) %> ago.
      <% if current_user?(feed_item.user) %>
      <%= link_to "delete", feed_item, method: :delete,
        confirm: "You sure?",
        title: feed_item.content %>
      <% end %>
    </span>
  </li>
<% end %>

app/views/shared/_feed_player.html.erb
<% full_url = "../assets/video/#{@video.url}" %>
<p><%= full_url %></p>

<video id="videoShow" controls width="<%= @video.width %>" height ="<%= @video.height %>" preload="auto" poster="<%= full_url %>.jpg">
  <source src="<%= full_url %>.mp4" type="video/mp4" />
  <source src="<%= full_url %>.ogv" type="video/ogg" />
  <p>Your browser does not support video</p>
  
</video>

app/views/shared/_micropost_form.html.erb
<%= form_for(@micropost) do |f| %>
  <div class="field">
    <%= f.text_area :content, placeholder: "Compose new micropost..." %>
  </div>
  <%= f.submit "Post", class: "btn btn-large btn-primary" %>
<% end %>

app/views/shared/_stats.html.erb
<% @user ||= current_user %>
<div class="stats">
  <a href="<%= following_user_path(@user) %>">
  <strong id="following" class="stat">
    <%= @user.followed_users.count %>
  </strong>
  following
  </a>
  <a href="<%= followers_user_path(@user) %>">
  <strong id="followers" class="stat">
    <%= @user.followers.count %>
  </strong>
  followers
  </a>
</div>

app/views/shared/_user_info.html.erb
<a href="<%= user_path(current_user) %>">
  <%= gravatar_for current_user %>
</a>
<h1>
  <%= current_user.name %>
</h1>

<span>
  <%= link_to "view my profile", current_user %>
</span>
<span>
  <%= pluralize(current_user.microposts.count, "micropost") %>
</span>

app/views/shared/_video_player.html.erb
<% full_url = "../assets/video/#{@video.url}" %>
<p><%= full_url %></p>

<video id="videoShow" width="<%= @video.width %>" height ="<%= @video.height %>" preload="auto" poster="<%= full_url %>.jpg">
  <source src="<%= full_url %>.mp4" type="video/mp4" />
  <source src="<%= full_url %>.ogv" type="video/ogg" />
  <p>Your browser does not support video</p>
  
</video>

<div id="video_controls">
  <div id="play_toggle" class="player-button">Play</div>
  <div id="progress">
    <div id="load_progress"></div>
    <div id="play_progress"></div>
  </div>
  <div id="time">
    <span id="current_time">00:00</span> /
    <span id="duration">00:00</span>
  </div> 
</div>

<script>
  $('#videoShow').bind("ended", function() {
    this.play();
  });
  
  $(function() {
    
    // doesnt render controls if HTML5 video type is not supported //
    if (!document.createElement('video').canPlayType) {
      $('#video_controls').hide();
      return;
    }

    var video = document.getElementById('videoShow');
    
    // Play/Pause button ===========================================//
    $("#play_toggle").bind('click', function() {
      if (video.paused) {
        video.play();
        $(this).html("Pause");
      } else {
        video.pause();
        $(this).html("Play");
      }
    });
    
    // Progress Bar code ===========================================//
    $("#videoShow").bind("timeupdate", function() {
      var timePercent = (this.currentTime / this.duration) * 100;
      $("#play_progress").css({ width : timePercent + "%" });
    });
    
    $(video).bind("progress", function() {
      updateLoadProgress(this);
    });
    $(video).bind("loadeddata", function() {
      updateLoadProgress(this);
    });
    $(video).bind("canplaythrough", function() {
      updateLoadProgress(this);
    });
    $(video).bind("playing", function() {
      updateLoadProgress(this);
    });
    
    function updateLoadProgress(video_player) {
      if (video_player.buffered.length > 0) {
        var percent = (video_player.buffered.end(0) / video_player.duration) * 100;
        $('#load_progress').css({ width: percent + '%'});
      } 
    }
    
    // Time Display ==================================================//
    $(video).bind("timeupdate", function() {
      $("#current_time").html(formatTime(this.currentTime));
    });
    $(video).bind("durationchange", function() {
      $("#duration").html(formatTime(this.duration));
    });
    function formatTime(seconds) {
      var seconds = Math.round(seconds);
      var minutes = Math.floor(seconds / 60);
      seconds = Math.floor(seconds % 60);
      minutes = (minutes >= 10) ? minutes : "0" + minutes;
      seconds = (seconds >= 10) ? seconds : "0" + seconds;
      return minutes + ":" + seconds;
    }
    
  });
  


</script>