config/routes.rb
Drivein::Application.routes.draw do
  
  resources :relationships
  resources :sessions, only: [:new, :create, :destroy]
  match '/signup', to: 'users#new'
  match '/signin', to: 'sessions#new'
  match '/signout', to: 'sessions#destroy', via: :delete
  resources :admins, only: [:new, :create, :destroy]
  root to: 'admins#hello'

  match '/about', to: 'home#about'
  match '/contact', to: 'home#contact'
  match '/home', to: 'home#index'
  match '/channel', to: 'home#channel'
  match '/learn', to: 'home#learn'
  match '/news', to: 'home#news'
  
  match '/theatre', to: 'wireframe#theatre'
  match '/screening_room', to: 'wireframe#screening_room'
  match '/cutting_room', to: 'wireframe#cutting_room'
  match '/suitcase', to: 'wireframe#suitcase'
  match '/tabloids', to: 'wireframe#tabloids'
  match '/surf', to: 'wireframe#surf'
  
  resources :microposts, only: [:create, :destroy]
  resources :relationships, only: [:create, :destroy]
  
  resources :users do 
    member do
      get :following, :followers
    end
  end
  

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  
  def index
    @users = User.order('id DESC')
    @page_name = PAGE_NAME
  end
  
  def help
    @page_name = PAGE_NAME
    
  end
  
  def contact
    @page_name = PAGE_NAME
    
  end

  def about
    @page_name = PAGE_NAME
    
  end
  
  def channel
    @micropost = current_user.microposts.build if signed_in?
    @feed_items = Micropost.all
    @page_name = PAGE_NAME
    
    
  end
  
  def learn
    @page_name = PAGE_NAME
    
  end
  
  def news
    @page_name = PAGE_NAME
    
  end
  



end

app/views/home/about.html.erb
<div class="center hero-unit">
  <div class="row">
    <h1>Welcome to <%= @page_name %></h1>
    <h2>
      <%= @page_name %> is a Festival Video game to be played by festival goers

    </h2>
    <% if !signed_in? %>
      <%= link_to "Sign up now!", signup_path, class: "btn btn-large btn-primary" %>
    <%  end %>
  </div>
</div>

app/views/home/channel.html.erb
<div class="center hero-unit">
<% if !signed_in? %>
  <div class="row">
    <h1>Welcome to <%= @page_name %>!</h1>
    <h2>
      Wibble is the best video sharing site and will soon replace all television networks worldwide

    </h2>
    <%= link_to "Sign up now!", signup_path, class: "btn btn-large btn-primary" %>
<% else %>
    <aside class="span8">
      <section>
        <%= render 'shared/user_info' %>
      </section>
      <section>
      <%= render 'shared/stats' %>
      </section>
      <section>
        <%= render 'shared/micropost_form' %>
      </section>
    </aside>
    <div class="span4">
      <h3>Micropost Feed</h3>
      <%= render 'shared/feed' %>
    </div>
<% end %>
  </div>
</div>

app/views/home/contact.html.erb
<div class="center hero-unit">
  <div class="row">
    <h2>Tech Support Info goes here</h2>
    <p>
      Phone Number to call for 24/7 support</p>
    <p>  Email to send questions into</p>
     <p> Chat now with a specialist </p>
    </p>
  </div>
</div>

app/views/home/index.html.erb
<div class="center hero-unit">
  <div class="row">
    <h1>Welcome to <%= @page_name %></h1>
    <% if signed_in? %>
      <h2>You are signed in as </h2>
      <%= render 'shared/user_info' %> 
      <p></p>
      <div><%= link_to "Not #{current_user.name}?", signout_path, method: "delete"%></div>
    <% else %>
      <table class="table table-striped">
        <thead>
          <td></td>
          <td><h2>Choose a User to Sign In As ...</h2></td>
          <td></td>
        </thead>
        <tbody>  
          <% @users.each do |u| %>
            <tr>
              <td><%= u.password %></td>
              <td><%= u.name %></td>
              <td>
                <%= link_to "Sign In As", sessions_path(email: u.email, page: 'development'), :class => 'btn btn-large btn-info', method: :post %>
              </td>
            </tr>
          <% end %>
          </tr>
          <tr>
            <td></td>
            <td>New User</td>
            <td><%= link_to "Sign Up", signup_path, class: "btn btn-large btn-success" %></td>
          </tr>
        </tbody>
      </table>
    <% end %>
  </div>
</div>

app/views/home/learn.html.erb
<div class="container">
    <div class="row-fluid">
      <div class="span2">    
      </div>
      <div class="center">
        <div class="span10">
          <h2>Learn How to Use this Platform</h2>
          <p>
            Links to tutorials on how to use all the features here.</p>
           <p> A channel of teaching the software available here to.</p>
           <p> You can watch tutorials or you can search topics and we'll make you a channel to watch.</p>
        </div>
      </div>
    </div>
</div>

app/views/home/news.html.erb
<div class="center hero-unit">
  <div class="row">
    <h2>Internet News Feeds</h2>
    <p>
      twitter feed </p>
    <p> Facebook link in</p>
     <p> google alerts and RSS </p>
    </p>
  </div>
</div>