config/routes.rb
Drivein::Application.routes.draw do
  
  resources :relationships
  resources :sessions, only: [:new, :create, :destroy]
  match '/signup', to: 'users#new'
  match '/signin', to: 'sessions#new'
  match '/signout', to: 'sessions#destroy', via: :delete
  resources :admins, only: [:new, :create, :destroy]
  root to: 'admins#hello'

  match '/about', to: 'home#about'
  match '/contact', to: 'home#contact'
  match '/home', to: 'home#index'
  match '/channel', to: 'home#channel'
  match '/learn', to: 'home#learn'
  match '/news', to: 'home#news'
  
  match '/theatre', to: 'wireframe#theatre'
  match '/screening_room', to: 'wireframe#screening_room'
  match '/cutting_room', to: 'wireframe#cutting_room'
  match '/suitcase', to: 'wireframe#suitcase'
  match '/tabloids', to: 'wireframe#tabloids'
  match '/surf', to: 'wireframe#surf'
  
  resources :microposts, only: [:create, :destroy]
  resources :relationships, only: [:create, :destroy]
  
  resources :users do 
    member do
      get :following, :followers
    end
  end
  

end

app/views/layouts/_footer.html.erb
<footer class="footer">
<small>
  <ul>
    <li><%= link_to "About", about_path %></li>
    <li><%= link_to "Contact", contact_path %></li>
    <li><%= link_to "News", news_path%></li>
  </ul>
</small>
<nav>
<% if signed_in? %>  
<ul>
  <li>Controllers:</li>
  <li><%= link_to "Users", users_path%></li>
</ul>
<% end %>
</nav>
</footer>

app/views/layouts/_header.html.erb
<% flash.each do |name, msg| %>
  <div class="alert alert-<%= name == :notice ? 'success' : 'error' %>">
    <a class="close" data-dismiss="alert" href="#">×</a>
    <%= msg %>
  </div>
<% end %>
<div class="navbar navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container">
      <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </a>
      <%= link_to image_tag("clapboard-icon.jpg"), home_path, {:class => "brand"} %>
      <div class="nav-collapse">
        <% if signed_in? %>
        <ul class="nav">
          
          <li><%= link_to "wf 1", theatre_path %></li>
          <li><%= link_to "wf 2", screening_room_path %></li>
          <li><%= link_to "wf 3", cutting_room_path %></li>
          <li><%= link_to "wf 4", suitcase_path %></li>
          <li><%= link_to "wf 5", learn_path %></li>
        </ul>
        <% end %>
        <ul class="nav pull-right">
          <% if signed_in? %>
            <li><%= link_to "Users", users_path %></li>
            <li id="fat-menu" class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">Account <b class="caret"></b></a>
                  <ul class="dropdown-menu">
                    <li><%= link_to "Profile", current_user %></li>
                    <li><%= link_to "Settings", edit_user_path(current_user) %></li>
                    <li class="divider"></li>
                    <li><%= link_to "Sign out", signout_path, method: "delete" %></li>
                  </ul>
            </li>
          <% else %>
            <li><%= link_to "Log Off", root_path %></li>
          <% end %>
        </ul> 
      </div>
    </div>
  </div>
</div>

app/views/layouts/_intro.html.erb
<% flash.each do |name, msg| %>
  <div class="alert alert-<%= name == :notice ? 'success' : 'error' %>">
    <a class="close" data-dismiss="alert" href="#">×</a>
    <%= msg %>
  </div>
<% end %>
<div class="navbar navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container">
      <%= link_to image_tag("clapboard-icon.jpg"), root_path, {:class => "brand"} %>
      <div class="nav-collapse">
      <ul class="nav pull-right">
         </ul> 
      </div>
    </div>
  </div>
</div>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= @page_name %></title>
  <%= render 'layouts/shim' %>
  <%= stylesheet_link_tag    "application", :media => "all" %>

  <%= javascript_include_tag "application" %>

  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body>

  <div class="container-fluid">
    <% if params[:controller] == 'admins' %>
      <%= render 'layouts/intro' %>
    <% else %>  
      <%= render 'layouts/header' %>
    <% end %>
    <div class="row-fluid">
      <div>
        <%= yield %>
      </div>
    </div>
    <% if params[:controller] != 'admins' %>
      <%= render 'layouts/footer' %>
    <% end %>

  </div>

</body>
</html>